x-app: &app
  build:
    context: .
  environment:
    - DATABASE_URL=postgres://app:app@db/app
    - DETECTION_URL  
  restart: on-failure

services:
  srv:
    <<: *app
    command:  bash -c "wait-for-it db:5432 -- yarn db-migrate up && yarn srv start"
    ports:
      - "${SERVER_PORT:-80}:80"
  db:
    image: "postgres:13"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
volumes:
  db-data:
