version: '3.4'


x-app: &app
  image: "${DOCKER_REGISTRY}/sivic/app"
  environment:
    - DATABASE_URL=postgres://app:app@db/app
    - DETECTION_API  
  restart: on-failure

services:
  srv:
    <<: *app
    command: wait-for-it db:5432 -- yarn srv start
    ports:
      - "${SERVER_PORT}:80"
    depends_on:
      - migration

  migration:
    <<: *app
    command: wait-for-it db:5432 -- yarn db-migrate up
    depends_on:
      - db
  db:
    image: "postgres:13"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
